/**
 * @file mock_macros.h
 *
 * @brief Auto generated mock implementation for the header file:
 *        macros.h
 *
 * THIS FILE WAS AUTOGENERATED ON 11/11/2020 BY MCMOCK DO NOT EDIT
 */


#ifndef INCLUDE_MOCK_MACROS_H
#define INCLUDE_MOCK_MACROS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "samples/xyz/macros.h"




/* UnitTest APIs for MIN() */
void mock_MIN_expect_and_return( X arg_X_a, Y arg_Y_b, #define retval );
void mock_MIN_ignore_arg_arg_X_a( void );
void mock_MIN_ignore_arg_arg_Y_b( void );

/* UnitTest APIs for MAX() */
void mock_MAX_expect_and_return( X arg_X_c, Y arg_Y_d, #define retval );
void mock_MAX_ignore_arg_arg_X_c( void );
void mock_MAX_ignore_arg_arg_Y_d( void );

/* UnitTest APIs for WARN_IF() */
void mock_WARN_IF_expect_and_return( EXP arg_EXP_e, #define retval );
void mock_WARN_IF_ignore_arg_arg_EXP_e( void );


#ifdef __cplusplus
}
#endif

#endif /* INCLUDE_MOCK_MACROS_H */
