/**
 * @file mock_abc.h
 *
 * @brief Auto generated mock implementation for the header file:
 *        abc.h
 *
 * THIS FILE WAS AUTOGENERATED ON 11/11/2020 BY MCMOCK DO NOT EDIT
 */


#ifndef INCLUDE_MOCK_ABC_H
#define INCLUDE_MOCK_ABC_H

#ifdef __cplusplus
extern "C" {
#endif

#include "samples/abc/abc.h"

#include "abc_types.h"



/* UnitTest APIs for abc_method() */
void mock_abc_method_expect_and_return( abc_int arg, abc_int_t retval );
void mock_abc_method_ignore_arg_arg( void );

/* UnitTest APIs for register_handler() */
void mock_register_handler_expect( abc_message_handler_t handler );
void mock_register_handler_ignore_arg_handler( void );


#ifdef __cplusplus
}
#endif

#endif /* INCLUDE_MOCK_ABC_H */
